name: kreels
region: sgp

# API Backend Service
services:
  - name: api
    dockerfile_path: api/Dockerfile
    source_dir: api
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET

# Web Frontend (Static Site)
static_sites:
  - name: web
    source_dir: KreelsMobile/dist
    routes:
      - path: /
    index_document: index.html
    error_document: index.html
    build_command: cd ../KreelsMobile && npm install && npx expo export --platform web
    output_dir: dist

# Managed PostgreSQL Database
databases:
  - name: db
    engine: PG
    production: false
    cluster_name: kreels-db
    db_name: kreels
    db_user: kreels_user
